name: solution_challange_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_without_text.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21


environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
  geocoding: ^2.2.0
  google_maps_flutter: ^2.5.3
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.2
  http: ^1.2.0
  image_picker: ^1.0.7
  jwt_decode: ^0.3.1
  provider: ^6.1.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  assets:
    - assets/storage-credentials.json
    - assets/logo.jpeg
    - assets/user_placeholder.png
    - assets/business_placeholder.png
    - assets/articles.json
  uses-material-design: true
