name: solution_challange_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
  geocoding: ^2.2.0
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  jwt_decode: ^0.3.1
  provider: ^6.1.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
